require("settings")
require("keybindings")
require("plugins")

require("nv-lspconfig")
require("nv-treesitter")
require("nv-clang-format")
require("nv-sneak")
require("nv-rust")
require("nv-nerdtree")
